<%-- 
    Document   : addnewauthor
    Created on : Mar 20, 2017, 3:00:14 PM
    Author     : koss
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<jsp:useBean id="author" class="beans.Author">
    <jsp:setProperty name="author" property="*"></jsp:setProperty> 
</jsp:useBean>
<jsp:useBean id="ebook" class="beans.Ebook">
    <jsp:setProperty name="ebook" property="*"></jsp:setProperty>
</jsp:useBean>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Add new author</title>
    </head>
    <body>
        <div>
            <form action="AddNewEbookAndAuthorServlet" method="post">
                <fieldset>
                    <legend>Author information:</legend>
                    ID: (autogenerated)<br>
                    <input type="text" name="author_id" value="${author.authorId}" readonly="readonly">
                    <br><br>
                    Name:<br>
                    <input type="text" name="author_name" placeholder="Please input author's name" required>
                    <br><br>
                    Surname:<br>
                    <input type="text" name="author_surname" placeholder="Please input author's surname" required>
                    <br><br>                    
                    <input type="reset" value="Reset">
                </fieldset>
                <br>
                <fieldset>
                    <legend>eBook information:</legend>
                    ISSN: (autogenerated)<br>
                    <input type="text" name="eb_issn" value="${ebook.ISSN}" readonly="readonly">
                    <br>
                    <span></span>
                    <%--<span><jsp:getProperty name="ebook" property="issn_error"/></span>--%>
                    <br><br>
                    Category:
                    <select name="eb_category">
                        <option value="Technical">Technical</option>
                        <option value="Novel">Novel</option>
                        <option value="Art album">Art album</option>
                    </select>
                    <br><br>
                    Title:<br>
                    <input type="text" name="eb_title" <%--value="${ebook.title}"--%> placeholder="Please input eBook title" autofocus required>
                    <%--<span><jsp:getProperty name="ebook" property="title_error"/></span>--%>
                    <br><br>
                    Number of pages:<br>
                    <input type="text" name="eb_noofpages" placeholder="Please input number of pages" required>
                    <br><br>
                    Price:<br>
                    <input type="text" name="eb_price" placeholder="Please input eBook price" required>
                    <br><br>        
                    <input type="reset" value="Reset">
                </fieldset>
                <br>
                <input type="submit" value="Submit">
                <input type="hidden" name="add_author" value="jsp_name" >
            </form>     
        </div>
    </body>
</html>
