<%-- 
    Document   : addnewebook
    Created on : Mar 17, 2017, 7:29:03 PM
    Author     : koss
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>
<jsp:useBean id="ebook" class="beans.Ebook" >
    <jsp:setProperty name ="ebook" property="*" />
</jsp:useBean>
<jsp:useBean id="author" class="beans.Author" >
    <jsp:setProperty name ="author" property="*" />
</jsp:useBean>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Add new eBook</title>
    </head>
    <body>
        <%-- <sql:setDataSource var="snapshot" driver="org.apache.derby.jdbc.ClientDriver"
                           url="jdbc:derby://localhost:1527/EBOOKSDB;create=true;"
                           user="kossT"  password="1411"/>
        <sql:update dataSource="${snapshot}" var="result">
            INSERT INTO EBOOKS(issn, title, category, number_of_pages, rating, price) VALUES (?,?,?,?,?,?)
            <sql:param value="${param.issn}" />
            <sql:param value="${param.title}" /> 
            <sql:param value="${param.category}" />            
            <sql:param value="${param.noofpages}" />                       
            <sql:param value="0" />
            <sql:param value="${param.price}" />
        </sql:update>

        <sql:update dataSource="${snapshot}" var="result">
            INSERT INTO AUTHORS(author_id, name, surname, issn) VALUES (?,?,?,?)
            <sql:param value="${param.author_id}" />            
            <sql:param value="${param.name}" />
            <sql:param value="${param.surname}" />
            <sql:param value="${param.issn}" />
        </sql:update>  --%>

        <div>
            <form action="AddNewEbookAndAuthorServlet" method="post">
                <fieldset>
                    <legend>eBook information:</legend>
                    ISSN: (autogenerated)<br>
                    <input type="text" name="eb_issn" value="${ebook.ISSN}" readonly="readonly">
                    <br>
                    <span></span>
                    <%--<span><jsp:getProperty name="ebook" property="issn_error"/></span>--%>
                    <br><br>
                    Category:
                    <select name="eb_category">
                        <option value="Technical">Technical</option>
                        <option value="Novel">Novel</option>
                        <option value="Art album">Art album</option>
                    </select>
                    <br><br>
                    Title:<br>
                    <input type="text" name="eb_title" <%--value="${ebook.title}"--%> placeholder="Please input eBook title" autofocus required>
                    <%--<span><jsp:getProperty name="ebook" property="title_error"/></span>--%>
                    <br><br>
                    Number of pages:<br>
                    <input type="text" name="eb_noofpages" placeholder="Please input number of pages" required>
                    <br><br>
                    Price:<br>
                    <input type="text" name="eb_price" placeholder="Please input eBook price" required>
                    <br><br>        
                    <input type="reset" value="Reset">
                </fieldset>
                <br>
                <fieldset>
                    <legend>Author information:</legend>
                    ID: (autogenerated)<br>
                    <input type="text" name="author_id" value="${author.authorId}" readonly="readonly">
                    <br><br>
                    Name:<br>
                    <input type="text" name="author_name" placeholder="Please input author's name" required>
                    <br><br>
                    Surname:<br>
                    <input type="text" name="author_surname" placeholder="Please input author's surname" required>
                    <br><br>
                    <input type="reset" value="Reset">                                        
                </fieldset>
                <input type="submit" name="admin_ebooks_insert" value="Insert">
                <input type="hidden" name="add_book" value="jsp_name" >
            </form> 
            <br><br>            
        </div>
    </body>
</html>
