<%-- 
    Document   : addnewebook
    Created on : Mar 17, 2017, 7:29:03 PM
    Author     : koss
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <sql:setDataSource var="snapshot" driver="org.apache.derby.jdbc.ClientDriver"
                           url="jdbc:derby://localhost:1527/EBOOKSDB;create=true;"
                           user="kossT"  password="1411"/>
        <sql:update dataSource="${snapshot}" var="result">
            INSERT INTO EBOOKS(isbn, categ_id, title, no_of_pages, rating, price) VALUES (?,?,?,?,?,?)
            <sql:param value="${param.isbn}" />
            <sql:param value="${param.category}" />
            <sql:param value="${param.title}" />
            <sql:param value="${param.noofpages}" />
            <sql:param value="0" />
            <sql:param value="${param.price}" />
        </sql:update>

        <sql:update dataSource="${snapshot}" var="result">
            INSERT INTO AUTHORS(author_id, isbn, name, surname) VALUES (?,?,?,?)
            <sql:param value="${param.id}" />
            <sql:param value="${param.isbn}" />
            <sql:param value="${param.name}" />
            <sql:param value="${param.surname}" />
        </sql:update>

        <div>
            <form action="${pageContext.request.contextPath}/AddnewebookServlet">
                <fieldset>
                    <legend>eBook information:</legend>
                    ISBN:<br>
                    <input type="text" name="isbn" placeholder="autogenerated">
                    <br><br>
                    Category:
                    <select name="category">
                        <option value="Technical">Technical</option>
                        <option value="Novel">Novel</option>
                        <option value="Art album">Art album</option>
                    </select>
                    <br><br>
                    Title:<br>
                    <input type="text" name="title" placeholder="Please input eBook title" autofocus required>
                    <br><br>
                    Number of pages:<br>
                    <input type="text" name="noofpages" placeholder="Please input number of pages" required>
                    <br><br>
                    Price:<br>
                    <input type="text" name="price" placeholder="Please input eBook price" required>
                    <br><br>
                </fieldset>
            </form>  
            <form>
                <fieldset>
                    <legend>Author information:</legend>
                    ID:<br>
                    <input type="text" name="id" placeholder="autogenerated">
                    <br><br>
                    Name:<br>
                    <input type="text" name="name" placeholder="Please input author's name" required>
                    <br><br>
                    Surname:<br>
                    <input type="text" name="surname" placeholder="Please input author's surname" required>
                    <br><br>
                </fieldset>
            </form>
            <br><br>
            <input type="submit" class="ebookstorebutton" name="admin_ebooks_insert" value="Insert" onclick="alert('New record submitted!')">
            <input type="reset" value="Reset">
        </div>
    </body>
</html>
